package com.zai.agent.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme - inspired by Material You expressive palette
val md_light_primary = Color(0xFF0B57D0)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFD3E4FF)
val md_light_onPrimaryContainer = Color(0xFF001D36)
val md_light_secondary = Color(0xFF565F71)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFDAE3F8)
val md_light_onSecondaryContainer = Color(0xFF131C2B)
val md_light_tertiary = Color(0xFF6F5677)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFFAD8FF)
val md_light_onTertiaryContainer = Color(0xFF28132F)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFFDFCFF)
val md_light_onBackground = Color(0xFF1A1C1E)
val md_light_surface = Color(0xFFFDFCFF)
val md_light_onSurface = Color(0xFF1A1C1E)
val md_light_surfaceVariant = Color(0xFFDFE2EB)
val md_light_onSurfaceVariant = Color(0xFF42474E)
val md_light_outline = Color(0xFF73777F)
val md_light_outlineVariant = Color(0xFFC3C7CF)
val md_light_scrim = Color(0xFF000000)
val md_light_inverseSurface = Color(0xFF2F3033)
val md_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_light_inversePrimary = Color(0xFFA1C9FF)
val md_light_surfaceDim = Color(0xFFDAD9DD)
val md_light_surfaceBright = Color(0xFFFDFCFF)
val md_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_light_surfaceContainerLow = Color(0xFFF4F3F7)
val md_light_surfaceContainer = Color(0xFFEEEDEE)
val md_light_surfaceContainerHigh = Color(0xFFE8E8E9)
val md_light_surfaceContainerHighest = Color(0xFFE2E2E4)

// Dark scheme
val md_dark_primary = Color(0xFFA1C9FF)
val md_dark_onPrimary = Color(0xFF003258)
val md_dark_primaryContainer = Color(0xFF00497D)
val md_dark_onPrimaryContainer = Color(0xFFD3E4FF)
val md_dark_secondary = Color(0xFFBEC7DC)
val md_dark_onSecondary = Color(0xFF283041)
val md_dark_secondaryContainer = Color(0xFF3E4759)
val md_dark_onSecondaryContainer = Color(0xFFDAE3F8)
val md_dark_tertiary = Color(0xFFDDBCE4)
val md_dark_onTertiary = Color(0xFF3F2847)
val md_dark_tertiaryContainer = Color(0xFF563E5E)
val md_dark_onTertiaryContainer = Color(0xFFFAD8FF)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF1A1C1E)
val md_dark_onBackground = Color(0xFFE2E2E5)
val md_dark_surface = Color(0xFF1A1C1E)
val md_dark_onSurface = Color(0xFFE2E2E5)
val md_dark_surfaceVariant = Color(0xFF42474E)
val md_dark_onSurfaceVariant = Color(0xFFC3C7CF)
val md_dark_outline = Color(0xFF8D9199)
val md_dark_outlineVariant = Color(0xFF42474E)
val md_dark_scrim = Color(0xFF000000)
val md_dark_inverseSurface = Color(0xFFE2E2E5)
val md_dark_inverseOnSurface = Color(0xFF2F3033)
val md_dark_inversePrimary = Color(0xFF0B57D0)
val md_dark_surfaceDim = Color(0xFF1A1C1E)
val md_dark_surfaceBright = Color(0xFF414244)
val md_dark_surfaceContainerLowest = Color(0xFF15161719)
val md_dark_surfaceContainerLow = Color(0xFF232528)
val md_dark_surfaceContainer = Color(0xFF272A2C)
val md_dark_surfaceContainerHigh = Color(0xFF323437)
val md_dark_surfaceContainerHighest = Color(0xFF3D3F42)

// User bubble colors
val userBubbleLight = Color(0xFF0B57D0)
val userBubbleDark = Color(0xFF00497D)
val assistantBubbleLight = Color(0xFFEEEDEE)
val assistantBubbleDark = Color(0xFF272A2C)
